### ISSUE TITLE
Вопрос про joomla-memorials

### ISSUE THREAD

**Issue by juliadyachuk** [joomplace/joomla-memorials#1]
Здравствуйте, коллеги
 
С Наступающим!
 
Я попыталась скачать с github пакет [joomla-memorials](https://github.com/joomplace/joomla-memorials), но при установке в joomla  пишет:
Пути установки не существует.
Пакет: Установка: В процессе установки произошла ошибка: com_joomportfolio.zip.
 
Можно это как-то исправить?
 
И еще вопрос. Я хотела бы, чтобы компонент работал с платными подписчиками. Планирую продавать через Virtuemart.  Могли бы вы сделать мне доступ к расширенным функциям memorials сразу после оплаты? Я заплачу за вашу работу:)
 
Я есть в телеге @Iuliia_domamarket
 
Если сойдемся по цене и срокам, то от меня еще будут заказы.
 
Надеюсь на быстрый ответ. Еще раз с Наступающим Новым годом.
Спасибо.
 
 
________________
С уважением,
Юлия Дьячук - директор ООО «Сфера-Про»,
 
Телефон, WhatsApp, Viber: +7(922) 209-38-46
email: [bvista@ya.ru](mailto:bvista@ya.ru)
 
Страница ФБ: https://www.facebook.com/julia.dyachuk

**Comment by fsvblr** [comment]
Hi Julia.
The package must be downloaded from the releases page - https://github.com/joomplace/joomla-memorials/releases , and not through the green "code" button.
Brief instruction page - https://joomplace.com/github.html .

**Comment by juliadyachuk** [comment]
Hello, Serguei 
Thanks for the quick response.
 I downloaded  pkg_memorials_2.2.1.zip  and started the installation on the site. 

Here is the answer: WarningJInstaller: :Install: Could not find the XML file to install the package.Table 'madeinural_lapida.#__jp3_field' doesn't existPackage: Installation: An error occurred during installation: com_joomportfolio.zip

**Comment by juliadyachuk** [comment]
Dear Serguei. 
Modules and protocols are installed normally. 
Problem with COM_JOOMPORTFOLIO_DESC component. This has not been established from any of the reported cases. 

Could you help me? Thank you.

**Comment by fsvblr** [comment]
Dear Julia, our support has responded to you at bvista@ya.ru .
Happy New Year.
